version: '3.8'
services:
  app:
    image: mazmun  # replace with your application image name
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/food_delivery
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_REDIS_HOST: redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: food_delivery
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
