version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123

      # Redis Configuration
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      
      # Application settings
      SPRING_SECURITY_EXPIRATION_MS: 31622400000
      SPRING_SECURITY_KEY: sdjfn2n3iunf2309hjn3uenfiun24hwe982h3iuwefkjsdsf23
      DELIVERY_RADIUS: 10000.0
      IMAGE_UPLOAD_PATH: /images/
      BOT_NAME: food_delivery909_bot
      BOT_TOKEN: 6169217907:AAGrfa9k4zG7Mhv8kLkmu7NNAmtj0H5eWfo
      ORDER_DELETE_CRON: "0 0 2 * * ?"

      # Domain
      MAIN_DOMAIN: http://127.0.0.1:8080/api

    depends_on:
      - db
      - redis
    volumes:
      - ./images:/images  # Map local images directory to the container

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
